services:
    backend:
        image: homework2:0.1
        environment:
            BACK_PORT: 8081 
            BACK_URL:  
            MODE: BE 
            CUBIX_HOMEWORK: MarkgruberF  
            APP_DEFAULT_MESSAGE: 
            
    frontend: 
        image: homework2:0.1
        ports:
        - 8080:8080
        environment:
            BACK_PORT: 
            BACK_URL:  http://backend:8081
            MODE: FE 
            CUBIX_HOMEWORK: MarkgruberF  
            APP_DEFAULT_MESSAGE: 