services:
    backend:
        image: backapp:0.1
             
    frontend: 
        image: frontapp:0.1
        ports:
        - 8080:8080
        environment:
            BACK_URL:  http://backend:8081